import 'package:flutter/material.dart';
import '../services/language_service.dart';
import 'package:provider/provider.dart';

class AppLocalizations {
  final BuildContext context;
  AppLocalizations(this.context);

  static AppLocalizations of(BuildContext context) => AppLocalizations(context);

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'AK Finserv',
      'login': 'Login',
      'mobile_number': 'Mobile Number',
      'worker_name': 'Worker Name',
      'error_name': 'Please enter your name',
      'username': 'Username',
      'business_name': 'Business Name',
      'password': 'Password',
      'pin': 'PIN',
      'settings': 'Settings',
      'language': 'Language',
      'select_language': 'Select Language',
      'tamil': 'Tamil',
      'english': 'English',
      'admin_login': 'Admin Login',
      'worker_login': 'Worker Login',
      'field_agent': 'Field Agent',
      'home': 'Home',
      'menu': 'Menu',
      'admin_auth_subtitle': 'Administrative Access Only',
      'worker_auth_subtitle': 'Field Staff Authentication',
      'web_offline_unavailable': 'Connection required for web login.',
      'dashboard': 'Dashboard',
      'add_worker': 'Add Worker',
      'audit_logs': 'Audit Logs',
      'logout': 'Logout',
      'success': 'Success',
      'failure': 'Failure',
      'error_password': 'Password is required',
      'save': 'Save',
      'cancel': 'Cancel',
      'skip': 'Skip',
      'face_registration': 'Face Registration',
      'capture': 'Capture',
      'retake': 'Retake',
      'save_face': 'Save Face',
      'area': 'Area / Group',
      'address': 'Address',
      'id_proof': 'ID Proof',
      'create_worker': 'Create Worker',
      'name_required': 'Name, Mobile and 4-digit PIN are required',
      'worker_added': 'Worker Added Successfully',
      'worker_qr': 'Worker QR Code',
      'qr_info': 'QR Code for Identity Verification',
      'qr_footer': 'Scan this QR code to verify worker details.',
      'done': 'Done',
      'welcome': 'Welcome',
      'enter_pin': 'Enter your PIN',
      'biometric_error': 'Biometrics not available on this device',
      'biometric_reason': 'Please authenticate to login',
      'biometric_login': 'Login with Biometrics',
      'logged_offline': 'Logged in offline',
      'invalid_pin': 'Invalid PIN',
      'confirm_pin': 'Confirm PIN',
      'set_pin': 'Set 4-Digit PIN',
      'pin_usage_info': 'You will need this PIN for daily login',
      'change': 'Change',
      'continue': 'Continue',
      'device_bound': 'Device Bound',
      'reset_binding': 'Reset Device Binding',
      'reset_confirm_title': 'Reset Device Binding?',
      'reset_confirm_content': 'This will allow worker to login on a new device.',
      'no_area': 'No Area',
      'no_logs': 'No Logs Found',
      'device_label': 'Device',
      'device_binding_reset': 'Device binding reset',
      'login_success': 'Login success',
      'access_denied': 'Access Denied',
      'invalid_password': 'Invalid Password',
      'worker_created': 'Worker created successfully',
      'face_registered': 'Face registered successfully',
      'connection_failed': 'Connection failed. Check network.',
      'server_error': 'Server error. Please try again later.',
      'error': 'An error occurred',
      'user_not_found': 'User not found in local records',
      'user_inactive': 'User account is inactive',
      'worker_dashboard': 'Worker Dashboard',
      'quick_actions': 'Quick Actions',
      'recent_activity': 'Recent Activity',
      'collected': 'Collected',
      'goal': 'Today\'s Goal',
      'performance': 'Performance',
      'qr_scan': 'QR Scan',
      'collection': 'Collection',
      'expense': 'Expense',
      'reports': 'Reports',
      'user_management': 'User Management',
      'active': 'Active',
      'inactive': 'Inactive',
      'locked': 'Locked',
      'search_users': 'Search Users...',
      'edit_user': 'Edit User',
      'save_changes': 'Save Changes',
      'status': 'Status',
      'user_deactivated': 'User Deactivated',
      'user_activated': 'User Activated',
      'confirm_status_change': 'Confirm status change?',
      'all': 'All',
      'security': 'Security',
      'clear_biometrics': 'Clear Biometrics',
      'reset_pin': 'Reset PIN',
      'new_pin': 'New PIN',
      'biometrics_cleared': 'Biometric data cleared',
      'pin_reset_success': 'PIN reset successfully',
      'reset_device_binding': 'Reset Device Binding',
      'confirm_biometric_clear': 'Are you sure you want to clear biometric data? This will force the user to re-register their face.',
      'enter_new_pin': 'Enter New 4-digit PIN',
      'delete_user': 'Delete User',
      'delete_confirm_title': 'Delete Account?',
      'delete_confirm_content': 'This will permanently remove the worker account and all associated data. This action cannot be undone.',
      'user_deleted': 'User deleted successfully',
      'total': 'Total',
      'bio': 'Bio',
      'users': 'Users',
      'export_csv': 'Export to CSV',
      'select_mode': 'Select Mode',
      'select_all': 'Select All',
      'view_details': 'View Details',
      'activate': 'Activate',
      'deactivate': 'Deactivate',
      'delete': 'Delete',
      'actions': 'Actions',
      'registered': 'Registered',
      'not_registered': 'Not Registered',
      'biometric_status': 'Biometric Status',
      'face_registered_status': 'Face Registered',
      'activity_stats': 'Activity & Statistics',
      'total_logins': 'Total Logins',
      'failed': 'Failed',
      'last_login_label': 'Last Login:',
      'never': 'Never',
      'devices_count': 'Devices',
      'trusted': 'Trusted',
      'qr_code_label': 'QR Code',
      'user_qr_identification': 'User Identification QR Code',
      'selected': 'selected',
      'my_profile': 'My Profile',
      'security_hub': 'Security Hub',
      'my_team': 'My Team',
      'performance_analytics': 'Performance Analytics',
      'assigned_manager': 'Assigned Manager',
      'not_assigned': 'Not Assigned',
      'login_activity': 'Login Activity (Last 7 Days)',
      'biometric_adoption': 'Biometric Adoption',
      'role_distribution': 'Role Distribution',
      'loading_stats': 'Loading analytics...',
      'profile_updated': 'Profile updated successfully',
      'team_status': 'Team Status',
      'active_agents': 'Active Agents',
      'inactive_agents': 'Inactive Agents',
      'collection_review': 'Collection Review',
      'financial_analytics': 'Financial Analytics',
      'review': 'Review',
      'line_management': 'Line Management',
      'manage_lines': 'Manage Lines',
      'add_line': 'Add New Line',
      'line_name': 'Line Name',
      'assign_agent': 'Assign Agent',
      'sequence': 'Sequence',
      'lock_line': 'Lock Line',
      'unlock_line': 'Unlock Line',
      'add_customer_to_line_label': 'Add Customer',
      'reorder_customers': 'Reorder Sequence',
      'create': 'Create',
      'no_lines_found': 'No lines found. Tap + to create one.',
      'manage_customers': 'Manage Customers',
      'add_customer': 'Add Customer',
      'available_customers': 'Available Customers',
      'customer_added': 'Customer added to line',
      'reorder_success': 'Sequence updated successfully',
      'create_line': 'Create Line',
      'my_lines': 'My Lines',
      'daily_route': 'Daily Route',
      'name': 'Name',
      'create_customer': 'Create Customer',
      'loan_approvals': 'Loan Approvals',
      'collection_ledger': 'Collection Ledger',
      'risk_predictions': 'Risk Predictions',
      'worker_ai_performance': 'Worker AI Performance',
      'security_compliance': 'Security & Compliance',
      'security_compliance_title': 'Security & Compliance',
      'data_integrity': 'Data Integrity & Tamper Check',
      'role_abuse': 'Role Abuse & Velocity Alerts',
      'device_monitoring': 'Device Monitoring',
      'requires_face_verification': 'Security Check: Face ID Required',
      'system_configuration': 'System Configuration',
      'enrollment_guide': 'Position your face in the oval',
      'check_photo': 'Check if photo is clear',
      'collection_window_closed': 'Collection window is closed',
      'already_collected_today': 'Already collected for today',
      'collection_history': 'Collection History',
    },
    'ta': {
      'app_title': 'வசூல் டிரைவ்',
      'login': 'உள்நுழை',
      'mobile_number': 'மொபைல் எண்',
      'worker_name': 'பணியாளர் பெயர்',
      'error_name': 'உங்கள் பெயரை உள்ளிடவும்',
      'username': 'பயனர் பெயர்',
      'business_name': 'வணிக பெயர்',
      'password': 'கடவுச்சொல்',
      'pin': 'ரகசிய எண்',
      'settings': 'அமைப்புகள்',
      'language': 'மொழி',
      'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'tamil': 'தமிழ்',
      'english': 'ஆங்கிலம்',
      'admin_login': 'நிர்வாகி உள்நுழைவு',
      'worker_login': 'பணியாளர் உள்நுழைவு',
      'field_agent': 'களப் பணியாளர்',
      'home': 'முகப்பு',
      'menu': 'பட்டி',
      'admin_auth_subtitle': 'நிர்வாக அணுகல் மட்டுமே',
      'worker_auth_subtitle': 'களப்பணியாளர் அங்கீகாரம்',
      'web_offline_unavailable': 'இணைய இணைப்பு தேவை.',
      'dashboard': 'டாஷ்போர்டு',
      'add_worker': 'பணியாளர் சேர்க்க',
      'audit_logs': 'தணிக்கை பதிவுகள்',
      'logout': 'வெளியேறு',
      'success': 'வெற்றி',
      'failure': 'தோல்வி',
      'error_password': 'கடவுச்சொல் அவசியம்',
      'save': 'சேமி',
      'cancel': 'ரத்து செய்',
      'skip': 'தவிர்',
      'face_registration': 'முகம் பதிவு',
      'capture': 'புகைப்படம் எடுக்கவும்',
      'retake': 'மீண்டும் எடுக்கவும்',
      'save_face': 'முகத்தை சேமி',
      'area': 'பகுதி / ஊர்',
      'address': 'முகவரி',
      'id_proof': 'அடையாளச் சான்று எண்',
      'create_worker': 'பணியாளரை உருவாக்கு',
      'name_required': 'பெயர், மொபைல் மற்றும் 4 இலக்க பின் தேவை',
      'worker_added': 'பணியாளர் வெற்றிகரமாக சேர்க்கப்பட்டார்',
      'worker_qr': 'பணியாளர் QR கோட்',
      'qr_info': 'அடையாள சரிபார்ப்புக்கான QR கோட்',
      'qr_footer': 'இந்த QR கோடை ஸ்கேன் செய்து பணியாளர் விவரங்களைச் சரிபார்க்கலாம்.',
      'done': 'முடிந்தது',
      'welcome': 'வணக்கம்',
      'enter_pin': 'ரகசிய எண்ணை உள்ளிடவும்',
      'biometric_error': 'இந்த சாதனத்தில் விரல் ரேகை வசதி இல்லை',
      'biometric_reason': 'உள்நுழைய உங்கள் விரல் ரேகையை பயன்படுத்தவும்',
      'biometric_login': 'விரல் ரேகை மூலம் உள்நுழைய',
      'logged_offline': 'ஆஃப்லைனில் உள்நுழைந்தீர்கள்',
      'invalid_pin': 'தவறான ரகசிய எண்',
      'confirm_pin': 'ரகசிய எண்ணை உறுதிப்படுத்தவும்',
      'set_pin': '4 இலக்க ரகசிய எண் அமைக்கவும்',
      'pin_usage_info': 'தினமும் உள்நுழைய இந்த எண் தேவைப்படும்',
      'change': 'மாற்றவும்',
      'continue': 'தொடரவும்',
      'device_bound': 'சாதனம் இணைக்கப்பட்டுள்ளது',
      'reset_binding': 'சாதன இணைப்பை மீட்டமை',
      'reset_confirm_title': 'சாதன இணைப்பை மீட்டமைக்கவா?',
      'reset_confirm_content': 'இது பணியாளரை புதிய சாதனத்தில் உள்நுழைய அனுமதிக்கும்.',
      'no_area': 'பகுதி இல்லை',
      'no_logs': 'பதிவுகள் இல்லை',
      'device_label': 'சாதனம்',
      'device_binding_reset': 'சாதன பிணைப்பு நீக்கப்பட்டது',
      'login_success': 'வெற்றிகரமாக உள்நுழைந்தீர்கள்',
      'access_denied': 'அனுமதி இல்லை',
      'invalid_password': 'தவறான கடவுச்சொல்',
      'worker_created': 'பணியாளர் வெற்றிகரமாக சேர்க்கப்பட்டார்',
      'face_registered': 'முகம் வெற்றிகரமாக பதிவு செய்யப்பட்டது',
      'connection_failed': 'இணைப்பு தோல்வி. பிணையத்தைச் சரிபார்க்கவும்.',
      'server_error': 'சர்வர் பிழை. சிறிது நேரம் கழித்து மீண்டும் முயற்சிக்கவும்.',
      'error': 'ஒரு பிழை ஏற்பட்டது',
      'user_not_found': 'உள்ளூர் பதிவுகளில் பயனர் இல்லை',
      'user_inactive': 'பயனர் கணக்கு முடக்கப்பட்டுள்ளது',
      'worker_dashboard': 'பணியாளர் டேஷ்போர்டு',
      'quick_actions': 'விரைவான செயல்கள்',
      'recent_activity': 'சமீபத்திய செயல்பாடு',
      'collected': 'வசூலிக்கப்பட்டது',
      'goal': 'இன்றைய இலக்கு',
      'performance': 'செயல்திறன்',
      'qr_scan': 'கியூஆர் ஸ்கேன்',
      'collection': 'வசூல்',
      'expense': 'செலவு',
      'reports': 'அறிக்கைகள்',
      'user_management': 'பயனர் மேலாண்மை',
      'active': 'செயலில்',
      'inactive': 'செயலற்றது',
      'locked': 'பூட்டப்பட்டது',
      'search_users': 'பயனர்களைத் தேடுங்கள்...',
      'edit_user': 'பயனரைத் திருத்தவும்',
      'save_changes': 'மாற்றங்களைச் சேமிக்கவும்',
      'status': 'நிலை',
      'user_deactivated': 'பயனர் முடக்கப்பட்டுள்ளார்',
      'user_activated': 'பயனர் செயல்படுத்தப்பட்டார்',
      'confirm_status_change': 'நிலையை மாற்ற உறுதிப்படுத்துகிறீர்களா?',
      'all': 'அனைத்தும்',
      'security': 'பாதுகாப்பு',
      'clear_biometrics': 'பயோமெட்ரிக்ஸை அழி',
      'reset_pin': 'PIN-ஐ மீட்டமை',
      'new_pin': 'புதிய PIN',
      'biometrics_cleared': 'பயோமெட்ரிக் தரவு அழிக்கப்பட்டது',
      'pin_reset_success': 'PIN வெற்றிகரமாக மீட்டமைக்கப்பட்டது',
      'reset_device_binding': 'சாதன இணைப்பை மீட்டமைக்கவும்',
      'confirm_biometric_clear': 'பயோமெட்ரிக் தரவை நிச்சயமாக அழிக்க விரும்புகிறீர்களா? இது பயனரை மீண்டும் தனது முகத்தைப் பதிவு செய்ய வைக்கும்.',
      'enter_new_pin': 'புதிய 4-இலக்க PIN-ஐ உள்ளிடவும்',
      'delete_user': 'பயனரை நீக்கு',
      'delete_confirm_title': 'கணக்கை நீக்கவா?',
      'delete_confirm_content': 'இது பணியாளர் கணக்கு மற்றும் அதனுடன் தொடர்புடைய அனைத்து தரவையும் நிரந்தரமாக நீக்கிவிடும். இந்தச் செயலை மாற்ற முடியாது.',
      'user_deleted': 'பயனர் வெற்றிகரமாக நீக்கப்பட்டார்',
      'total': 'மொத்தம்',
      'bio': 'பயோ',
      'users': 'பயனர்கள்',
      'export_csv': 'CSV-க்கு ஏற்றுமதி',
      'select_mode': 'தேர்வு முறை',
      'select_all': 'அனைத்தையும் தேர்ந்தெடு',
      'view_details': 'விவரங்களைக் காண்க',
      'activate': 'செயல்படுத்து',
      'deactivate': 'முடக்கு',
      'delete': 'நீக்கு',
      'actions': 'செயல்கள்',
      'registered': 'பதிவு செய்யப்பட்டது',
      'not_registered': 'பதிவு செய்யப்படவில்லை',
      'biometric_status': 'பயோமெட்ரிக் நிலை',
      'face_registered_status': 'முகம் பதிவு செய்யப்பட்டது',
      'activity_stats': 'செயல்பாடு மற்றும் புள்ளிவிவரங்கள்',
      'total_logins': 'மொத்த உள்நுழைவுகள்',
      'failed': 'தோல்வி',
      'last_login_label': 'கடைசி உள்நுழைவு:',
      'never': 'ஒருபோதும் இல்லை',
      'devices_count': 'சாதனங்கள்',
      'trusted': 'நம்பகமானது',
      'qr_code_label': 'QR குறியீடு',
      'user_qr_identification': 'பயனர் அடையாள QR குறியீடு',
      'selected': 'தேர்ந்தெடுக்கப்பட்டது',
      'my_profile': 'எனது ப்ரொபைல்',
      'security_hub': 'பாதுகாப்பு மையம்',
      'my_team': 'எனது குழு',
      'performance_analytics': 'செயல்திறன் பகுப்பாய்வு',
      'assigned_manager': 'ஒதுக்கப்பட்ட நிர்வாகி',
      'not_assigned': 'ஒதுக்கப்படவில்லை',
      'login_activity': 'உள்நுழைவு செயல்பாடு (கடந்த 7 நாட்கள்)',
      'biometric_adoption': 'பயோமெட்ரிக் தத்தெடுப்பு',
      'role_distribution': 'பங்கு விநியோகம்',
      'loading_stats': 'பகுப்பாய்வு ஏற்றப்படுகிறது...',
      'profile_updated': 'புரோபைல் வெற்றிகரமாக புதுப்பிக்கப்பட்டது',
      'team_status': 'குழு நிலை',
      'active_agents': 'செயலில் உள்ள ஏஜெண்டுகள்',
      'inactive_agents': 'செயலற்ற ஏஜெண்டுகள்',
      'collection_review': 'வசூல் சரிபார்ப்பு',
      'financial_analytics': 'நிதி பகுப்பாய்வு',
      'review': 'மதிப்பாய்வு',
      'line_management': 'வரி மேலாண்மை',
      'manage_lines': 'வரிகளை நிர்வகி',
      'add_line': 'புதிய வரியைச் சேர்',
      'line_name': 'வரி பெயர்',
      'assign_agent': 'முகவரை நியமி',
      'sequence': 'வரிசை',
      'lock_line': 'வரியைப் பூட்டு',
      'unlock_line': 'பூட்டைத் திற',
      'add_customer_to_line_label': 'வாடிக்கையாளரைச் சேர்',
      'reorder_customers': 'வரிசையை மாற்று',
      'create': 'உருவாக்கு',
      'no_lines_found': 'வரிகள் எதுவும் இல்லை. புதிய வரியை உருவாக்க + ஐத் தொடவும்.',
      'manage_customers': 'வாடிக்கையாளர்களை நிர்வகி',
      'add_customer': 'வாடிக்கையாளரைச் சேர்',
      'available_customers': 'கிடைக்கக்கூடிய வாடிக்கையாளர்கள்',
      'customer_added': 'வாடிக்கையாளர் வரிசையில் சேர்க்கப்பட்டார்',
      'reorder_success': 'வரிசை வெற்றிகரமாக புதுப்பிக்கப்பட்டது',
      'create_line': 'வரியை உருவாக்கு',
      'my_lines': 'எனது வரிகள்',
      'daily_route': 'தினசரி பாதை',
      'name': 'பெயர்',
      'create_customer': 'வாடிக்கையாளரை உருவாக்கு',
      'loan_approvals': 'கடன் அங்கீகாரங்கள்',
      'collection_ledger': 'வசூல் பேரேடு',
      'risk_predictions': 'இடர் கணிப்புகள்',
      'worker_ai_performance': 'பணியாளர் AI செயல்திறன்',
      'security_compliance': 'பாதுகாப்பு மற்றும் இணக்கம்',
      'security_compliance_title': 'பாதுகாப்பு மற்றும் இணக்கம்',
      'data_integrity': 'தரவு ஒருமைப்பாடு மற்றும் சேத சோதனையாக்கம்',
      'role_abuse': 'பத்திரிகை முறைமீறல் மற்றும் வேக எச்சரிக்கைகள்',
      'device_monitoring': 'சாதன கண்காணிப்பு',
      'requires_face_verification': 'பாதுகாப்புச் சோதனை: முகம் அடையாளம் தேவை',
      'system_configuration': 'கணினி கட்டமைப்பு',
      'enrollment_guide': 'உங்கள் முகத்தை வட்டத்தில் வைக்கவும்',
      'check_photo': 'புகைப்படம் தெளிவாக உள்ளதா என சரிபார்க்கவும்',
      'collection_window_closed': 'வசூல் நேரம் முடிந்தது',
      'already_collected_today': 'இன்று ஏற்கனவே வசூலிக்கப்பட்டது',
      'collection_history': 'வசூல் வரலாறு',
    },
  };

  String translate(String key) {
    String languageCode = Provider.of<LanguageProvider>(context, listen: false).currentLocale.languageCode;
    return _localizedValues[languageCode]?[key] ?? key;
  }
}

// Extension to make it easier to use in widgets: context.translate('key')
extension LocalizationExtension on BuildContext {
  String translate(String key) => AppLocalizations.of(this).translate(key);
}
