import 'package:flutter/material.dart';
import '../services/language_service.dart';
import 'package:provider/provider.dart';

class AppLocalizations {
  final BuildContext context;
  AppLocalizations(this.context);

  static AppLocalizations of(BuildContext context) => AppLocalizations(context);

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Vasool Drive',
      'login': 'Login',
      'mobile_number': 'Mobile Number',
      'worker_name': 'Worker Name',
      'error_name': 'Please enter your name',
      'username': 'Username',
      'business_name': 'Business Name',
      'password': 'Password',
      'pin': 'PIN',
      'settings': 'Settings',
      'language': 'Language',
      'select_language': 'Select Language',
      'tamil': 'Tamil',
      'english': 'English',
      'admin_login': 'Admin Login',
      'worker_login': 'Worker Login',
      'field_agent': 'Field Agent',
      'admin_auth_subtitle': 'Administrative Access Only',
      'worker_auth_subtitle': 'Field Staff Authentication',
      'web_offline_unavailable': 'Connection required for web login.',
      'dashboard': 'Dashboard',
      'add_worker': 'Add Worker',
      'audit_logs': 'Audit Logs',
      'logout': 'Logout',
      'success': 'Success',
      'failure': 'Failure',
      'error_mobile': 'Enter a valid 10-digit mobile number',
      'error_password': 'Password is required',
      'save': 'Save',
      'cancel': 'Cancel',
      'skip': 'Skip',
      'face_registration': 'Face Registration',
      'capture': 'Capture',
      'retake': 'Retake',
      'save_face': 'Save Face',
      'worker_name': 'Worker Name',
      'area': 'Area / Group',
      'address': 'Address',
      'id_proof': 'ID Proof',
      'create_worker': 'Create Worker',
      'name_required': 'Name, Mobile and 4-digit PIN are required',
      'worker_added': 'Worker Added Successfully',
      'worker_qr': 'Worker QR Code',
      'qr_info': 'QR Code for Identity Verification',
      'qr_footer': 'Scan this QR code to verify worker details.',
      'done': 'Done',
      'welcome': 'Welcome',
      'enter_pin': 'Enter your PIN',
      'biometric_error': 'Biometrics not available on this device',
      'biometric_reason': 'Please authenticate to login',
      'biometric_login': 'Login with Biometrics',
      'logged_offline': 'Logged in offline',
      'invalid_pin': 'Invalid PIN',
      'confirm_pin': 'Confirm PIN',
      'set_pin': 'Set 4-Digit PIN',
      'pin_usage_info': 'You will need this PIN for daily login',
      'change': 'Change',
      'otp_arrived': 'OTP has arrived',
      'enter_otp': 'Enter the OTP',
      'confirm': 'Confirm',
      'invalid_otp': 'Invalid OTP',
      'continue': 'Continue',
      'device_bound': 'Device Bound',
      'reset_binding': 'Reset Device Binding',
      'reset_confirm_title': 'Reset Device Binding?',
      'reset_confirm_content': 'This will allow worker to login on a new device.',
      'no_area': 'No Area',
      'no_logs': 'No Logs Found',
      'device_label': 'Device',
      'device_binding_reset': 'Device binding reset',
      'login_success': 'Login success',
      'access_denied': 'Access Denied',
      'invalid_password': 'Invalid Password',
      'worker_created': 'Worker created successfully',
      'face_registered': 'Face registered successfully',
      'connection_failed': 'Connection failed. Check network.',
      'server_error': 'Server error. Please try again later.',
      'error': 'An error occurred',
      'user_not_found': 'User not found in local records',
      'user_inactive': 'User account is inactive',
      'worker_dashboard': 'Worker Dashboard',
      'quick_actions': 'Quick Actions',
      'recent_activity': 'Recent Activity',
      'collected': 'Collected',
      'goal': 'Today\'s Goal',
      'performance': 'Performance',
      'qr_scan': 'QR Scan',
      'collection': 'Collection',
      'expense': 'Expense',
      'reports': 'Reports',
    },
    'ta': {
      'app_title': 'வசூல் டிரைவ்',
      'login': 'உள்நுழை',
      'mobile_number': 'மொபைல் எண்',
      'worker_name': 'பணியாளர் பெயர்',
      'error_name': 'உங்கள் பெயரை உள்ளிடவும்',
      'username': 'பயனர் பெயர்',
      'business_name': 'வணிக பெயர்',
      'password': 'கடவுச்சொல்',
      'pin': 'ரகசிய எண்',
      'settings': 'அமைப்புகள்',
      'language': 'மொழி',
      'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'tamil': 'தமிழ்',
      'english': 'ஆங்கிலம்',
      'admin_login': 'நிர்வாகி உள்நுழைவு',
      'worker_login': 'பணியாளர் உள்நுழைவு',
      'field_agent': 'களப் பணியாளர்',
      'admin_auth_subtitle': 'நிர்வாக அணுகல் மட்டுமே',
      'worker_auth_subtitle': 'களப்பணியாளர் அங்கீகாரம்',
      'web_offline_unavailable': 'இணைய இணைப்பு தேவை.',
      'dashboard': 'டாஷ்போர்டு',
      'add_worker': 'பணியாளர் சேர்க்க',
      'audit_logs': 'தணிக்கை பதிவுகள்',
      'logout': 'வெளியேறு',
      'success': 'வெற்றி',
      'failure': 'தோல்வி',
      'error_mobile': 'சரியான 10 இலக்க மொபைல் எண்ணை உள்ளிடவும்',
      'error_password': 'கடவுச்சொல் அவசியம்',
      'save': 'சேமி',
      'cancel': 'ரத்து செய்',
      'skip': 'தவிர்',
      'face_registration': 'முகம் பதிவு',
      'capture': 'புகைப்படம் எடுக்கவும்',
      'retake': 'மீண்டும் எடுக்கவும்',
      'save_face': 'முகத்தை சேமி',
      'worker_name': 'பணியாளர் பெயர்',
      'area': 'பகுதி / ஊர்',
      'address': 'முகவரி',
      'id_proof': 'அடையாளச் சான்று எண்',
      'create_worker': 'பணியாளரை உருவாக்கு',
      'name_required': 'பெயர், மொபைல் மற்றும் 4 இலக்க பின் தேவை',
      'worker_added': 'பணியாளர் வெற்றிகரமாக சேர்க்கப்பட்டார்',
      'worker_qr': 'பணியாளர் QR கோட்',
      'qr_info': 'அடையாள சரிபார்ப்புக்கான QR கோட்',
      'qr_footer': 'இந்த QR கோடை ஸ்கேன் செய்து பணியாளர் விவரங்களைச் சரிபார்க்கலாம்.',
      'done': 'முடிந்தது',
      'welcome': 'வணக்கம்',
      'enter_pin': 'ரகசிய எண்ணை உள்ளிடவும்',
      'biometric_error': 'இந்த சாதனத்தில் விரல் ரேகை வசதி இல்லை',
      'biometric_reason': 'உள்நுழைய உங்கள் விரல் ரேகையை பயன்படுத்தவும்',
      'biometric_login': 'விரல் ரேகை மூலம் உள்நுழைய',
      'logged_offline': 'ஆஃப்லைனில் உள்நுழைந்தீர்கள்',
      'invalid_pin': 'தவறான ரகசிய எண்',
      'confirm_pin': 'ரகசிய எண்ணை உறுதிப்படுத்தவும்',
      'set_pin': '4 இலக்க ரகசிய எண் அமைக்கவும்',
      'pin_usage_info': 'தினமும் உள்நுழைய இந்த எண் தேவைப்படும்',
      'change': 'மாற்றவும்',
      'otp_arrived': 'OTP வந்துள்ளது',
      'enter_otp': 'OTP ஐ உள்ளிடவும்',
      'confirm': 'உறுதிப்படுத்து',
      'invalid_otp': 'தவறான OTP',
      'continue': 'தொடரவும்',
      'device_bound': 'சாதனம் இணைக்கப்பட்டுள்ளது',
      'reset_binding': 'சாதன இணைப்பை மீட்டமை',
      'reset_confirm_title': 'சாதன இணைப்பை மீட்டமைக்கவா?',
      'reset_confirm_content': 'இது பணியாளரை புதிய சாதனத்தில் உள்நுழைய அனுமதிக்கும்.',
      'no_area': 'பகுதி இல்லை',
      'no_logs': 'பதிவுகள் இல்லை',
      'device_label': 'சாதனம்',
      'device_binding_reset': 'சாதன பிணைப்பு நீக்கப்பட்டது',
      'login_success': 'வெற்றிகரமாக உள்நுழைந்தீர்கள்',
      'access_denied': 'அனுமதி இல்லை',
      'invalid_password': 'தவறான கடவுச்சொல்',
      'worker_created': 'பணியாளர் வெற்றிகரமாக சேர்க்கப்பட்டார்',
      'face_registered': 'முகம் வெற்றிகரமாக பதிவு செய்யப்பட்டது',
      'connection_failed': 'இணைப்பு தோல்வி. பிணையத்தைச் சரிபார்க்கவும்.',
      'server_error': 'சர்வர் பிழை. சிறிது நேரம் கழித்து மீண்டும் முயற்சிக்கவும்.',
      'error': 'ஒரு பிழை ஏற்பட்டது',
      'user_not_found': 'உள்ளூர் பதிவுகளில் பயனர் இல்லை',
      'user_inactive': 'பயனர் கணக்கு முடக்கப்பட்டுள்ளது',
      'worker_dashboard': 'பணியாளர் டேஷ்போர்டு',
      'quick_actions': 'விரைவான செயல்கள்',
      'recent_activity': 'சமீபத்திய செயல்பாடு',
      'collected': 'வசூலிக்கப்பட்டது',
      'goal': 'இன்றைய இலக்கு',
      'performance': 'செயல்திறன்',
      'qr_scan': 'கியூஆர் ஸ்கேன்',
      'collection': 'வசூல்',
      'expense': 'செலவு',
      'reports': 'அறிக்கைகள்',
    },
  };

  String translate(String key) {
    String languageCode = Provider.of<LanguageProvider>(context, listen: false).currentLocale.languageCode;
    return _localizedValues[languageCode]?[key] ?? key;
  }
}

// Extension to make it easier to use in widgets: context.translate('key')
extension LocalizationExtension on BuildContext {
  String translate(String key) => AppLocalizations.of(this).translate(key);
}
